# Generated by Django 3.2.9 on 2022-01-29 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creador',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
