# Generated by Django 3.2.6 on 2022-03-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_creador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('pk',)},
        ),
    ]
