# Generated by Django 3.2.9 on 2022-02-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0005_alter_loan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicional', models.PositiveIntegerField()),
                ('date_created', models.DateField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
