version: '3.8'

services:
  web:
    build: ./pawnshop
    container_name: Django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pawnshop/:/usr/src/pawnshop/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pawnshop
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pawnshop_dev

volumes:
  postgres_data: