# Generated by Django 3.2.9 on 2022-01-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('abonos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
    ]
