# Generated by Django 3.2.9 on 2022-02-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20220129_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='monto_a_pagar',
        ),
    ]
