# Generated by Django 3.2.9 on 2022-02-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_monto_a_pagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('pk',)},
        ),
    ]
