# Generated by Django 3.2.6 on 2022-03-21 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options'),
        ('loans', '0005_alter_loan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_para_pago', models.DateField()),
                ('cuota_mensual', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000)])),
                ('date_de_pago', models.DateField()),
                ('retrasado', models.BooleanField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.estadopago')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
