# Generated by Django 3.2.6 on 2022-03-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options'),
        ('loans', '0006_estadopago_loandates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanDates',
            new_name='LoanDate',
        ),
    ]
